// LTA Questionnaire Configuration - Complete 90+ Questions with Full Logic
const LTA_QUESTIONNAIRE = {
    title: "Limpopo Tourism Agency Marketing & Program Efficacy Assessment",
    version: "2025.1",
    sections: {
        screening: {
            id: "screening",
            title: "Screening & Demographics",
            description: "Establish stakeholder profile and demographic information"
        },
        awareness: {
            id: "awareness",
            title: "Awareness",
            description: "Explore awareness and recall of LTA's marketing initiatives"
        },
        interest: {
            id: "interest", 
            title: "Interest",
            description: "Assess interest and emotional engagement generated by LTA's marketing"
        },
        consideration: {
            id: "consideration",
            title: "Consideration", 
            description: "Evaluate conversion from awareness to active consideration"
        },
        action: {
            id: "action",
            title: "Action",
            description: "Measure actual engagement behaviors and conversion"
        },
        advocacy: {
            id: "advocacy",
            title: "Advocacy",
            description: "Assess word-of-mouth behavior and brand ambassador potential"
        },
        optimization: {
            id: "optimization", 
            title: "Strategic Evaluation & Optimization",
            description: "Gather expert strategic assessment and recommendations"
        }
    },
    questions: [
        // ===== SCREENING & DEMOGRAPHICS =====
        {
            id: "q1",
            section: "screening",
            type: "single-select",
            text: "Which of the following best describes your primary professional role?",
            rationale: "Establishes stakeholder category for analysis segmentation and skip logic routing.",
            options: [
                "Marketing & Communications Professional (brand strategy, digital marketing, media planning, PR)",
                "Event Management & Experience Design Specialist", 
                "Tourism Industry Operator (accommodation, tours, activities, attractions)",
                "Trade & Distribution Partner (travel agent, tour operator, airline, transport, OTA, loyalty program)",
                "Regional/Municipal Tourism Representative (RTO, municipal tourism office)",
                "Content Creator & Media (journalist, blogger, influencer, photographer)",
                "Academic & Research Expert (tourism research, destination management, community development)",
                { value: "other", text: "Other (please specify)", requiresInput: true }
            ],
            required: true,
            logic: {
                setsStakeholderType: true
            }
        },
        {
            id: "q2",
            section: "screening", 
            type: "single-select",
            text: "How many years of experience do you have working in tourism, hospitality, marketing, or related fields?",
            rationale: "Establishes expertise level to weight responses and identify patterns by experience.",
            options: [
                "Less than 2 years",
                "2-5 years", 
                "6-10 years",
                "11-15 years", 
                "More than 15 years"
            ],
            required: true
        },
        {
            id: "q3",
            section: "screening",
            type: "single-select", 
            text: "What is your primary geographic location?",
            rationale: "Critical for understanding geographic perspectives and proximity market insights.",
            options: [
                "Limpopo Province",
                "Gauteng Province", 
                { value: "other_sa", text: "Other South African Province (please specify)", requiresInput: true },
                { value: "sadc", text: "SADC Country (please specify)", requiresInput: true },
                { value: "international", text: "International (please specify country)", requiresInput: true }
            ],
            required: true
        },
        {
            id: "q4",
            section: "screening",
            type: "multiple-select",
            text: "Which of the following best describes your relationship to Limpopo tourism?",
            rationale: "Establishes depth and nature of connection to inform interpretation of responses.", 
            options: [
                "I actively market/promote Limpopo as a destination",
                "I operate a tourism business in Limpopo",
                "I've attended LTA events or initiatives in the past year",
                "I sell/package Limpopo tourism products to clients", 
                "I create content about Limpopo tourism",
                "I conduct research on Limpopo tourism",
                "I've personally visited Limpopo for leisure in the past 2 years",
                "I've visited Limpopo for business/professional purposes in the past 2 years",
                "I have professional knowledge of Limpopo tourism but limited direct engagement",
                { value: "other", text: "Other (please specify)", requiresInput: true }
            ],
            required: true,
            maxSelections: 5
        },
        {
            id: "q5",
            section: "screening", 
            type: "single-select",
            text: "In the past 12 months, how would you rate your level of exposure to Limpopo Tourism Agency's marketing initiatives, campaigns, or events?",
            rationale: "Qualifying question to ensure sufficient awareness for meaningful evaluation; identifies reach gaps.",
            options: [
                "Extensive exposure (regularly encounter LTA content/initiatives)",
                "Moderate exposure (occasionally encounter LTA content/initiatives)", 
                "Minimal exposure (rarely encounter LTA content/initiatives)",
                "No exposure (have not encountered LTA content/initiatives)"
            ],
            required: true,
            logic: {
                routing: {
                    "No exposure (have not encountered LTA content/initiatives)": { section: "screening", question: "q7" }
                }
            }
        },
        {
            id: "q6",
            section: "screening",
            type: "multiple-select", 
            text: "Through which channels have you encountered Limpopo Tourism Agency content, campaigns, or initiatives in the past 12 months?",
            rationale: "Maps channel exposure to inform media mix optimization and identify most effective touchpoints.",
            options: [
                "Social media (Facebook, Instagram, Twitter/X, LinkedIn, TikTok)",
                "LTA website or mobile site",
                "Television advertising or programs", 
                "Radio advertising or programs",
                "Print media (newspapers, magazines, advertorials)",
                "Outdoor advertising (billboards, transit ads)",
                "Trade shows or exhibitions",
                "Industry events or forums", 
                "Media familiarization tours",
                "Direct email or newsletters",
                "PR coverage (news articles, features, reviews)",
                "Word of mouth (colleagues, industry contacts)",
                "Tourism product packaging or collateral", 
                "In-destination signage or materials",
                "Partnership channels (airlines, hotels, tour operators)",
                { value: "other", text: "Other (please specify)", requiresInput: true }
            ],
            required: false,
            maxSelections: 8,
            logic: {
                showOnlyIf: { question: "q5", notValue: "No exposure (have not encountered LTA content/initiatives)" }
            }
        },
        {
            id: "q7",
            section: "screening",
            type: "single-select",
            text: "What is your age range?",
            rationale: "Demographic segmentation for pattern analysis.", 
            options: [
                "18-24", "25-34", "35-44", "45-54", "55-64", "65+", "Prefer not to say"
            ],
            required: false
        },

        // ===== SECTION 1: AWARENESS =====
        {
            id: "q8", 
            section: "awareness",
            type: "open-ended",
            text: "Without prompting, what campaigns, initiatives, or messaging from the Limpopo Tourism Agency can you recall from the past 12 months? Please describe anything that comes to mind, even if only vague impressions.",
            rationale: "Unaided recall measures the strength of campaign memorability and message penetration.",
            required: false,
            inputType: "textarea",
            placeholder: "Describe any campaigns, messaging, or initiatives you recall...",
            logic: {
                showOnlyIf: { question: "q5", notValue: "No exposure (have not encountered LTA content/initiatives)" }
            }
        },
        {
            id: "q9",
            section: "awareness",
            type: "matrix",
            text: "Are you aware of any of the following Limpopo Tourism Agency initiatives or campaigns from 2025? Please indicate your level of awareness.",
            rationale: "Aided recall across major 2025 initiatives to measure reach and identify which programs achieved awareness.",
            rows: [
                "Tourism Month 'Discover Your Limpopo in Spring' Campaign (August-September 2025)",
                "Limpopo Wildlife Resorts (LWR) Mahala Week (free entrance to 11 nature reserves)", 
                "SANParks Week collaboration (free entrance to Kruger, Marakele, Mapungubwe)",
                "Limpopo Holiday Fair (Tourism exhibition)",
                "Mapungubwe Heritage Music Festival",
                "Tourism Thursdays Campaign (promoting hidden gems)", 
                "Limpopo Provincial Investment Conference (Tourism focus)",
                "Explore Tourism Limpopo (SMME showcase and industry dialogues)",
                "Various regional tourism exhibitions (Capricorn, Vhembe, etc.)"
            ],
            columns: [
                "Not aware at all",
                "Vaguely aware (heard of it but know little about it)", 
                "Somewhat aware (know basic details)",
                "Very aware (familiar with details and objectives)",
                "Extensively aware (deeply familiar, may have participated/engaged)",
                "Not applicable to my role/region"
            ],
            required: false,
            logic: {
                showOnlyIf: { question: "q5", notValue: "No exposure (have not encountered LTA content/initiatives)" }
            }
        },
        {
            id: "q10",
            section: "awareness",
            type: "single-select",
            text: "The Limpopo Tourism Agency's 2025 Tourism Month campaign theme was 'Tourism and Sustainable Transformation.' How clearly do you understand what this theme means in the context of Limpopo tourism?",
            rationale: "Tests whether thematic messaging is landing with clarity and meaning.",
            options: [
                "Not clear at all - I don't understand what this theme means",
                "Slightly clear - I have a vague sense but it's not well defined",
                "Moderately clear - I understand the basic concept",
                "Very clear - I have a good understanding of what this means",
                "Extremely clear - I fully understand and could explain this to others",
                "Not aware of this theme"
            ],
            required: false,
            logic: {
                showOnlyIf: { question: "q5", notValue: "No exposure (have not encountered LTA content/initiatives)" }
            }
        },
        {
            id: "q11",
            section: "awareness",
            type: "open-ended",
            text: "From your perspective, what do you believe 'Tourism and Sustainable Transformation' means for Limpopo? What impression or meaning does this theme convey to you?",
            rationale: "Qualitative exploration of theme interpretation to assess alignment with intended messaging.",
            required: false,
            inputType: "textarea",
            placeholder: "Share your interpretation of what this theme means...",
            logic: {
                showOnlyIf: { 
                    question: "q10", 
                    notValues: ["Not clear at all - I don't understand what this theme means", "Not aware of this theme"] 
                }
            }
        },
        {
            id: "q12",
            section: "awareness",
            type: "matrix",
            text: "How aware are you that Limpopo tourism offers diverse product clusters beyond traditional eco-tourism? Please indicate your awareness of each cluster.",
            rationale: "Measures success in communicating product diversity beyond eco-tourism positioning.",
            rows: [
                "Mega Conservation (biosphere reserves, conservation projects, natural attractions)",
                "Golf & Game (safari experiences combined with golfing)",
                "Special Interest (adventure activities, R&R/spa experiences, cultural tourism)",
                "Family & Recreation (bundled experiences for families and groups)",
                "Hunting & Safari (hunting packages and outdoor experiences)",
                "MICE (Meetings, Incentives, Conferences, Events/business tourism)"
            ],
            columns: [
                "Not aware at all",
                "Slightly aware",
                "Moderately aware",
                "Very aware",
                "Extensively aware - I actively promote/work with this cluster"
            ],
            required: false
        },
        {
            id: "q13",
            section: "awareness",
            type: "multiple-select",
            text: "Which of the following statements about Limpopo as a tourism destination were you aware of BEFORE taking this survey?",
            rationale: "Tests awareness of key differentiators and selling points LTA aims to communicate.",
            options: [
                "Limpopo has the highest tourism growth rate in South Africa",
                "Limpopo is only a 2-hour drive from Johannesburg",
                "Limpopo is a gateway to SADC countries",
                "Limpopo has 11 nature reserves with diverse ecosystems",
                "Limpopo has three UNESCO Biosphere Reserves",
                "Limpopo offers 20+ golf courses including signature courses",
                "Limpopo hosts major heritage and music festivals",
                "Limpopo has rich cultural heritage including the Rain Queen (Modjaji)",
                "Limpopo offers access to Kruger National Park through multiple gates",
                "Limpopo is home to Mapungubwe National Park (UNESCO World Heritage Site)",
                "None of the above",
                { value: "other", text: "I was aware of other distinctive aspects (please specify)", requiresInput: true }
            ],
            required: false,
            maxSelections: 5
        },
        {
            id: "q14",
            section: "awareness",
            type: "open-ended",
            text: "When you think of Limpopo as a tourism destination, what words, images, or feelings come to mind? Please be as specific as possible.",
            rationale: "Captures unaided brand associations and emotional resonance to understand current positioning.",
            required: false,
            inputType: "textarea",
            placeholder: "Describe the words, images, or feelings that come to mind..."
        },
        {
            id: "q15",
            section: "awareness",
            type: "likert-scale",
            text: "On a scale of 1-7, how would you rate Limpopo's distinctiveness compared to other South African tourism destinations?",
            rationale: "Quantifies perceived differentiation, addressing LTA's concern about lack of stand-out factor.",
            options: [
                { value: "1", label: "1 - Not distinctive at all (blends in with other provinces)" },
                { value: "2", label: "2" },
                { value: "3", label: "3" },
                { value: "4", label: "4 - Moderately distinctive" },
                { value: "5", label: "5" },
                { value: "6", label: "6" },
                { value: "7", label: "7 - Extremely distinctive (stands out clearly)" },
                { value: "unable", label: "Unable to assess" }
            ],
            required: false
        },
        {
            id: "q16",
            section: "awareness",
            type: "open-ended",
            text: "What makes Limpopo distinctive as a tourism destination? OR if you believe it lacks distinctiveness, what is preventing it from standing out?",
            rationale: "Qualitative depth on differentiation to identify what's working or what barriers exist.",
            required: false,
            inputType: "textarea",
            placeholder: "Explain what makes Limpopo distinctive or what prevents it from standing out..."
        },
        {
            id: "q17",
            section: "awareness",
            type: "single-select",
            text: "Are you aware that Limpopo has been referred to as 'South Africa's best kept secret'?",
            rationale: "Tests awareness of existing informal positioning to assess if it should be embraced or evolved.",
            options: [
                "Yes, I'm aware of this positioning",
                "No, I wasn't aware of this positioning",
                "I've heard something similar but not this exact phrase"
            ],
            required: false
        },
        {
            id: "q18",
            section: "awareness",
            type: "single-select",
            text: "From a marketing perspective, do you believe positioning Limpopo as 'South Africa's best kept secret' is:",
            rationale: "Expert assessment of whether 'best kept secret' positioning helps or hinders LTA's objectives.",
            options: [
                "Very effective - it creates intrigue and exclusivity",
                "Somewhat effective - it has some appeal but also limitations",
                "Neither effective nor ineffective",
                "Somewhat ineffective - it limits awareness and growth potential",
                "Very ineffective - it works against marketing objectives",
                "Unsure"
            ],
            required: false,
            logic: {
                showOnlyIf: { question: "q17", value: "Yes, I'm aware of this positioning" }
            }
        },
        {
            id: "q19",
            section: "awareness",
            type: "ranking",
            text: "Which marketing channels or touchpoints have been MOST effective in building your awareness of Limpopo tourism offerings? Please rank your top 3, with 1 being most effective.",
            rationale: "Identifies which channels drive awareness most effectively to optimize media investment.",
            options: [
                "Social media platforms",
                "Traditional media coverage (TV, radio, print news/features)",
                "LTA advertising campaigns",
                "Trade shows and exhibitions",
                "Industry events and forums",
                "Word of mouth from industry colleagues",
                "Direct experience (visiting Limpopo)",
                "Tourism product operators' own marketing",
                "Partnership channels (airlines, hotels, booking platforms)",
                "Travel media and influencer content",
                "LTA website and digital content",
                "Email newsletters and direct communications",
                { value: "other", text: "Other" }
            ],
            required: false,
            maxRank: 3
        },

        // ===== SECTION 2: INTEREST =====
        {
            id: "q20",
            section: "interest",
            type: "single-select",
            text: "To what extent has Limpopo Tourism Agency's marketing content sparked your personal or professional interest in Limpopo as a destination?",
            rationale: "Measures conversion from awareness to interest, critical step in engagement funnel.",
            options: [
                "Not at all - LTA content has not generated any interest",
                "Slightly - Minimal interest generated",
                "Moderately - Some interest generated",
                "Significantly - Strong interest generated",
                "Extremely - Very strong interest, actively seeking more information",
                "Not applicable - I haven't encountered LTA marketing content"
            ],
            required: false,
            logic: {
                showOnlyIf: { question: "q5", notValue: "No exposure (have not encountered LTA content/initiatives)" }
            }
        },
        {
            id: "q21",
            section: "interest",
            type: "matrix",
            text: "Please indicate your level of interest in the following types of events and experiences promoted by LTA in 2025.",
            rationale: "Maps interest across event portfolio to identify which offerings have strongest appeal.",
            rows: [
                "Heritage festivals and cultural celebrations",
                "Music festivals and concerts",
                "Nature and conservation experiences (birding, hiking, wildlife viewing)",
                "Adventure and outdoor activities (4x4, mountain biking, marathons)",
                "Food and beverage experiences (culinary events, markets, tastings)",
                "Arts and crafts exhibitions",
                "Sporting events (golf, rugby, marathons, angling competitions)",
                "Wellness and relaxation experiences (spa, retreat offerings)",
                "Business/MICE events (conferences, investment forums)",
                "Community and family-friendly events",
                "Educational tourism experiences (cultural villages, museums, heritage sites)"
            ],
            columns: [
                "Not at all interested",
                "Slightly interested",
                "Moderately interested",
                "Very interested",
                "Extremely interested",
                "Not applicable to my target market/role"
            ],
            required: false
        },
        {
            id: "q22",
            section: "interest",
            type: "open-ended",
            text: "Thinking about the Tourism Month 2025 events calendar, which specific events captured your attention or generated the most interest? Please name up to 3 events and briefly explain what made them appealing.",
            rationale: "Identifies standout events and the factors that drive interest for program optimization.",
            required: false,
            inputType: "textarea",
            placeholder: "List up to 3 events and explain why they were appealing...",
            logic: {
                showOnlyIf: { 
                    question: "q9", 
                    hasMatrixResponse: true,
                    minAwareness: "Somewhat aware (know basic details)"
                }
            }
        },
        {
            id: "q23",
            section: "interest",
            type: "open-ended",
            text: "Were there any events or initiatives in the 2025 calendar that you felt were missing or should be included? What additional offerings would generate interest from your perspective or your target market?",
            rationale: "Crowdsources ideas for event programming gaps and unmet market needs.",
            required: false,
            inputType: "textarea",
            placeholder: "Describe any missing events or initiatives that would generate interest..."
        },
        {
            id: "q24",
            section: "interest",
            type: "single-select",
            text: "How appealing do you find Limpopo's positioning as a destination offering diverse experiences for different market segments (not just eco-tourism)?",
            rationale: "Tests appeal of strategic shift away from eco-tourism-only positioning.",
            options: [
                "Not at all appealing - This positioning doesn't resonate",
                "Slightly appealing - Limited appeal",
                "Moderately appealing - Reasonably attractive",
                "Very appealing - Strong appeal",
                "Extremely appealing - Highly compelling and differentiated",
                "Unaware of this positioning"
            ],
            required: false
        },
        {
            id: "q25",
            section: "interest",
            type: "multiple-select",
            text: "Which market segments do you believe would find Limpopo's current tourism offerings MOST interesting and compelling?",
            rationale: "Validates whether LTA's segment targeting aligns with stakeholder perceptions of market fit.",
            options: [
                "International leisure travelers (US, UK, Germany, Europe)",
                "SADC leisure travelers (Zimbabwe, Botswana, Mozambique, etc.)",
                "Domestic leisure travelers (Gauteng and other provinces)",
                "Weekend break seekers from neighboring provinces",
                "Visiting Friends & Relatives (VFR) travelers",
                "Eco-warriors and conservation-minded travelers",
                "Wildlife and safari enthusiasts",
                "Adventure seekers and outdoor enthusiasts",
                "Golfers",
                "Cultural tourism enthusiasts",
                "Heritage and history buffs",
                "Business travelers and MICE market",
                "Wellness and R&R seekers",
                "Family travelers with children",
                "Young couples and honeymooners",
                "Retirees and mature travelers",
                "Budget-conscious travelers seeking value",
                "Luxury travelers",
                "Birding enthusiasts",
                "Hunting enthusiasts",
                "Faith-based/religious tourism travelers",
                { value: "other", text: "Other (please specify)", requiresInput: true }
            ],
            required: false,
            maxSelections: 5
        },
        {
            id: "q26",
            section: "interest",
            type: "open-ended",
            text: "Conversely, which market segments do you believe are currently UNDER-served or insufficiently appealed to by Limpopo's tourism marketing?",
            rationale: "Identifies opportunity gaps in segment targeting.",
            required: false,
            inputType: "textarea",
            placeholder: "Describe which market segments are under-served..."
        },
        {
            id: "q27",
            section: "interest",
            type: "ranking",
            text: "If you were describing Limpopo to a potential visitor or client, which aspects would you emphasize to generate the most interest? Please rank your top 5.",
            rationale: "Identifies which value propositions resonate most strongly for market communication.",
            options: [
                "Proximity and accessibility (close to Johannesburg, gateway to SADC)",
                "Wildlife and safari experiences (including Kruger National Park)",
                "Natural beauty and diverse ecosystems",
                "Cultural heritage and authentic experiences",
                "Adventure and outdoor activities",
                "Value for money compared to other destinations",
                "Uncrowded, off-the-beaten-path experiences",
                "Wellness and relaxation offerings",
                "Golf and recreational activities",
                "Conservation and sustainability focus",
                "Heritage sites and historical significance",
                "Food and culinary experiences",
                "Shopping and nightlife",
                "Events and festivals",
                "Weather and climate",
                "Safety and hospitality",
                { value: "other", text: "Other (please specify)", requiresInput: true }
            ],
            required: false,
            maxRank: 5
        },
        {
            id: "q28",
            section: "interest",
            type: "likert-scale",
            text: "On a scale of 1-7, how memorable would you say LTA's marketing campaigns and messaging have been over the past year?",
            rationale: "Quantifies memorability, key indicator of creative effectiveness.",
            options: [
                { value: "1", label: "1 - Not memorable at all" },
                { value: "2", label: "2" },
                { value: "3", label: "3" },
                { value: "4", label: "4 - Moderately memorable" },
                { value: "5", label: "5" },
                { value: "6", label: "6" },
                { value: "7", label: "7 - Extremely memorable" },
                { value: "no_exposure", label: "Haven't been exposed to LTA campaigns" }
            ],
            required: false,
            logic: {
                showOnlyIf: { question: "q5", notValue: "No exposure (have not encountered LTA content/initiatives)" }
            }
        },
        {
            id: "q29",
            section: "interest",
            type: "open-ended",
            text: "Can you describe a specific moment, message, visual, or campaign from LTA that stood out to you or stuck in your memory? What made it memorable?",
            rationale: "Captures what drives memorability to inform creative strategy and amplify successful elements.",
            required: false,
            inputType: "textarea",
            placeholder: "Describe a specific memorable moment or campaign element...",
            logic: {
                showOnlyIf: { 
                    question: "q28", 
                    value: ["4", "5", "6", "7"] 
                }
            }
        },
        {
            id: "q30",
            section: "interest",
            type: "open-ended",
            text: "On the flip side, what aspects of LTA's marketing or messaging FAILED to generate interest or fell flat with you or your target market?",
            rationale: "Critical feedback on what doesn't work to inform optimization and avoid ineffective approaches.",
            required: false,
            inputType: "textarea",
            placeholder: "Describe what didn't work or failed to generate interest..."
        },

        // ===== SECTION 3: CONSIDERATION =====
        {
            id: "q31",
            section: "consideration",
            type: "multiple-select",
            text: "Has your awareness of and interest in LTA's marketing led you to actively consider Limpopo for any of the following?",
            rationale: "Measures consideration conversion and identifies which types of engagement are being considered.",
            options: [
                "Personal leisure travel",
                "Business travel or conference attendance",
                "Recommending to clients/customers",
                "Developing tourism packages or products",
                "Partnership or collaboration opportunities",
                "Content creation or media coverage",
                "Investment or business development",
                "Research or academic study",
                "Event attendance (Tourism Month or other LTA events)",
                "Relocation or business establishment in Limpopo",
                { value: "other", text: "Yes, but for other reasons (please specify)", requiresInput: true },
                "No, I have not actively considered Limpopo despite awareness"
            ],
            required: false
        },
        {
            id: "q32",
            section: "consideration",
            type: "multiple-select",
            text: "You indicated that you have NOT actively considered Limpopo despite awareness of LTA's marketing. What are the primary barriers preventing you from moving from awareness/interest to active consideration?",
            rationale: "Critical diagnostic to understand conversion barriers from awareness/interest to consideration.",
            options: [
                "Lack of detailed information needed for decision-making",
                "Unclear value proposition compared to alternatives",
                "Accessibility concerns (flights, transportation, distance)",
                "Perception of limited offerings or things to do",
                "Price/affordability concerns",
                "Safety or security concerns",
                "Competing destinations are more appealing or familiar",
                "Lack of awareness among my clients/target market",
                "Insufficient infrastructure (accommodation, facilities)",
                "Seasonality or weather concerns",
                "Limited nightlife or entertainment options",
                "Perception that Limpopo is primarily for eco-tourism only",
                "Difficulty in booking or accessing products",
                "LTA's marketing hasn't been compelling enough",
                "Not relevant to my personal/professional needs",
                { value: "other", text: "Other (please specify)", requiresInput: true }
            ],
            required: false,
            logic: {
                showOnlyIf: { 
                    question: "q31", 
                    values: ["No, I have not actively considered Limpopo despite awareness"] 
                }
            }
        },
        {
            id: "q33",
            section: "consideration",
            type: "single-select",
            text: "How would you rate the VALUE PROPOSITION of Limpopo as a tourism destination compared to competing alternatives (other SA provinces or regional destinations)?",
            rationale: "Comparative assessment of competitiveness in marketplace.",
            options: [
                "Much weaker value proposition than alternatives",
                "Somewhat weaker value proposition than alternatives",
                "About the same value proposition as alternatives",
                "Somewhat stronger value proposition than alternatives",
                "Much stronger value proposition than alternatives",
                "Unable to assess"
            ],
            required: false
        },
        {
            id: "q34",
            section: "consideration",
            type: "open-ended",
            text: "What specific aspects make Limpopo's value proposition stronger or weaker than competing destinations?",
            rationale: "Qualitative depth on competitive positioning to identify strengths to leverage and weaknesses to address.",
            required: false,
            inputType: "textarea",
            placeholder: "Explain what makes Limpopo's value proposition stronger or weaker..."
        },
        {
            id: "q35",
            section: "consideration",
            type: "matrix",
            text: "How well does LTA's marketing address the following needs for different traveler types?",
            rationale: "Evaluates how well LTA is meeting diverse market needs, critical for broad appeal.",
            rows: [
                "International holiday makers seeking authentic African experiences",
                "SADC travelers looking for shopping, nightlife, and social experiences",
                "Domestic travelers visiting friends and relatives (VFR)",
                "Weekend break seekers from Gauteng/neighboring provinces",
                "Family travelers seeking diverse activities for all ages",
                "Business travelers and MICE market",
                "Adventure and outdoor enthusiasts",
                "Luxury travelers seeking premium experiences",
                "Budget-conscious travelers seeking value",
                "Solo travelers",
                "Limpopo residents exploring their own province"
            ],
            columns: [
                "Not addressed at all",
                "Poorly addressed",
                "Adequately addressed",
                "Well addressed",
                "Excellently addressed",
                "Not applicable to LTA's target markets"
            ],
            required: false
        },
        {
            id: "q36",
            section: "consideration",
            type: "open-ended",
            text: "One of LTA's strategic challenges is that Limpopo captures only 2% of international tourists, 5% of African tourists, and 9% of domestic tourists to South Africa. From your professional perspective, what is the single most significant factor limiting Limpopo's market capture?",
            rationale: "Expert diagnosis of the core issue limiting market share to guide strategic priorities.",
            required: false,
            inputType: "textarea",
            placeholder: "Describe the most significant factor limiting market capture..."
        },
        {
            id: "q37",
            section: "consideration",
            type: "single-select",
            text: "Another strategic concern is converting the 74% of domestic visitors who come for Visiting Friends & Relatives (VFR) into leisure travelers who explore and spend more in the province. How effectively do you believe LTA's marketing is addressing this opportunity?",
            rationale: "Assesses strategic approach to major conversion opportunity (VFR to leisure spending).",
            options: [
                "Not effectively at all - This opportunity is being missed",
                "Slightly effectively - Minimal effort toward this conversion",
                "Moderately effectively - Some initiatives but room for improvement",
                "Very effectively - Strong efforts to convert VFR to leisure",
                "Extremely effectively - Excellent strategy for VFR conversion",
                "Unaware of this opportunity or LTA's efforts"
            ],
            required: false
        },
        {
            id: "q38",
            section: "consideration",
            type: "open-ended",
            text: "What specific strategies or tactics would you recommend to convert VFR travelers into leisure explorers who extend their stays and increase spending in Limpopo?",
            rationale: "Crowdsources expert solutions to critical strategic challenge.",
            required: false,
            inputType: "textarea",
            placeholder: "Describe strategies to convert VFR travelers to leisure explorers..."
        },
        {
            id: "q39",
            section: "consideration",
            type: "single-select",
            text: "How adequate is the INFORMATION available about Limpopo tourism offerings for making informed decisions (whether for personal travel, client recommendations, or business purposes)?",
            rationale: "Evaluates information adequacy, essential for consideration and decision-making.",
            options: [
                "Severely inadequate - Critical information is missing or hard to find",
                "Somewhat inadequate - Important gaps in available information",
                "Adequate - Basic information is available",
                "Good - Most needed information is readily available",
                "Excellent - Comprehensive, accessible information is available",
                "Haven't sought information, unable to assess"
            ],
            required: false
        },
        {
            id: "q40",
            section: "consideration",
            type: "open-ended",
            text: "What specific information gaps or accessibility issues prevent you (or your clients/target market) from fully considering Limpopo?",
            rationale: "Identifies specific content and access needs to inform digital strategy and collateral development.",
            required: false,
            inputType: "textarea",
            placeholder: "Describe specific information gaps or accessibility issues...",
            logic: {
                showOnlyIf: { 
                    question: "q39", 
                    values: ["Severely inadequate - Critical information is missing or hard to find", "Somewhat inadequate - Important gaps in available information"] 
                }
            }
        },
        {
            id: "q41",
            section: "consideration",
            type: "likert-scale",
            text: "How clearly differentiated is Limpopo's brand positioning compared to other South African provinces (Western Cape, KwaZulu-Natal, Eastern Cape, etc.)?",
            rationale: "Quantifies perceived differentiation, addressing concern about lack of stand-out factor versus other provinces.",
            options: [
                { value: "1", label: "1 - Not differentiated at all (indistinguishable from other provinces)" },
                { value: "2", label: "2" },
                { value: "3", label: "3" },
                { value: "4", label: "4 - Moderately differentiated" },
                { value: "5", label: "5" },
                { value: "6", label: "6" },
                { value: "7", label: "7 - Extremely differentiated (very clear, unique positioning)" },
                { value: "unable", label: "Unable to assess" }
            ],
            required: false
        },
        {
            id: "q42",
            section: "consideration",
            type: "open-ended",
            text: "Complete this sentence: 'Limpopo is the tourism destination for travelers who want ______.'",
            rationale: "Projective technique to understand perceived positioning and identify potential positioning territories.",
            required: false,
            inputType: "text",
            placeholder: "Complete the sentence..."
        },

        // ===== SECTION 4: ACTION =====
        {
            id: "q43",
            section: "action",
            type: "multiple-select",
            text: "In the past 12 months, have you taken any of the following actions related to Limpopo tourism?",
            rationale: "Quantifies actual engagement behaviors to measure action conversion rates.",
            options: [
                "Visited Limpopo for leisure purposes",
                "Visited Limpopo for business/professional purposes",
                "Attended an LTA event (Tourism Month event, exhibition, forum, media tour, etc.)",
                "Recommended Limpopo to clients, friends, or family",
                "Booked/sold Limpopo tourism packages or products",
                "Created content about Limpopo (articles, blog posts, social media, photos, videos)",
                "Shared LTA content on social media or with networks",
                "Visited LTA's website or digital platforms",
                "Downloaded LTA materials or resources",
                "Entered into a partnership or collaboration with LTA",
                "Participated in LTA training or capacity-building programs",
                "Attended trade shows where LTA was exhibiting",
                "Engaged with LTA on social media (likes, comments, shares)",
                "Contacted LTA for information or support",
                "Made business investments or decisions related to Limpopo tourism",
                "None of the above",
                { value: "other", text: "Other actions (please specify)", requiresInput: true }
            ],
            required: false
        },
        {
            id: "q44",
            section: "action",
            type: "multiple-select",
            text: "Which of your actions (from Q43) were DIRECTLY influenced by LTA's marketing, events, or initiatives?",
            rationale: "Attributes actions to LTA efforts versus other influences.",
            options: [
                "Visited Limpopo for leisure purposes",
                "Visited Limpopo for business/professional purposes",
                "Attended an LTA event (Tourism Month event, exhibition, forum, media tour, etc.)",
                "Recommended Limpopo to clients, friends, or family",
                "Booked/sold Limpopo tourism packages or products",
                "Created content about Limpopo (articles, blog posts, social media, photos, videos)",
                "Shared LTA content on social media or with networks",
                "Visited LTA's website or digital platforms",
                "Downloaded LTA materials or resources",
                "Entered into a partnership or collaboration with LTA",
                "Participated in LTA training or capacity-building programs",
                "Attended trade shows where LTA was exhibiting",
                "Engaged with LTA on social media (likes, comments, shares)",
                "Contacted LTA for information or support",
                "Made business investments or decisions related to Limpopo tourism",
                "None - my actions were not influenced by LTA",
                { value: "other", text: "Other actions influenced by LTA", requiresInput: true }
            ],
            required: false,
            logic: {
                showOnlyIf: { 
                    question: "q43", 
                    notValues: ["None of the above"] 
                }
            }
        },
        {
            id: "q45",
            section: "action",
            type: "open-ended",
            text: "Please describe one specific action you took and how LTA's marketing or initiative influenced that decision.",
            rationale: "Captures conversion stories and influence pathways for case study development.",
            required: false,
            inputType: "textarea",
            placeholder: "Describe a specific action and how LTA influenced it...",
            logic: {
                showOnlyIf: { 
                    question: "q44", 
                    notValues: ["None - my actions were not influenced by LTA"] 
                }
            }
        },
        {
            id: "q46",
            section: "action",
            type: "single-select",
            text: "What was the PRIMARY FACTOR that converted your awareness/interest into actual action?",
            rationale: "Identifies the 'tipping point' factors that drive conversion from consideration to action.",
            options: [
                "Compelling content or creative messaging from LTA",
                "Specific event or initiative that was perfectly timed/relevant",
                "Accessibility of information and ease of planning",
                "Attractive pricing or value proposition",
                "Personal recommendation or word of mouth",
                "Partnership or collaboration opportunity",
                "Professional requirement or business opportunity",
                "Free or discounted access (e.g., LWR Mahala Week, SANParks Week)",
                "Desire to support local/regional tourism",
                "Existing familiarity or previous positive experience",
                { value: "other", text: "Other (please specify)", requiresInput: true }
            ],
            required: false,
            logic: {
                showOnlyIf: { 
                    question: "q43", 
                    notValues: ["None of the above"] 
                }
            }
        },
        {
            id: "q47",
            section: "action",
            type: "likert-scale",
            text: "On a scale of 1-7, how satisfied were you with your experience(s) related to Limpopo tourism in the past 12 months?",
            rationale: "Measures satisfaction with actual experiences, critical for advocacy and repeat behavior.",
            options: [
                { value: "1", label: "1 - Extremely dissatisfied" },
                { value: "2", label: "2" },
                { value: "3", label: "3" },
                { value: "4", label: "4 - Neither satisfied nor dissatisfied" },
                { value: "5", label: "5" },
                { value: "6", label: "6" },
                { value: "7", label: "7 - Extremely satisfied" },
                { value: "not_applicable", label: "Not applicable" }
            ],
            required: false,
            logic: {
                showOnlyIf: { 
                    question: "q43", 
                    notValues: ["None of the above"] 
                }
            }
        },
        {
            id: "q48",
            section: "action",
            type: "open-ended",
            text: "What aspects of your Limpopo tourism experience exceeded expectations, and what aspects fell short?",
            rationale: "Captures experience quality to identify strengths to amplify and gaps to address.",
            required: false,
            inputType: "textarea",
            placeholder: "Please address:\n- What exceeded expectations:\n- What fell short:\n- Suggestions for improvement:",
            logic: {
                showOnlyIf: { 
                    question: "q43", 
                    notValues: ["None of the above"] 
                }
            }
        },
        {
            id: "q49",
            section: "action",
            type: "multiple-select",
            text: "You indicated that you have not taken action related to Limpopo tourism in the past 12 months despite potential awareness of LTA initiatives. What are the primary reasons you did not convert awareness/interest into action?",
            rationale: "Critical diagnostic of conversion failure to identify barriers preventing action.",
            options: [
                "Insufficient time or opportunity",
                "Budget constraints",
                "Prioritized other destinations",
                "Lack of compelling reason to act",
                "Insufficient information to make decisions",
                "Accessibility or logistical barriers",
                "LTA's marketing didn't resonate with my needs/interests",
                "Unaware of specific action opportunities",
                "Professional circumstances didn't align (e.g., wrong target market for my business)",
                "Concerns about value for money",
                "Safety or security concerns",
                "Personal circumstances (health, family, work commitments)",
                "Simply haven't gotten around to it yet (intention exists)",
                "Not applicable - Limpopo tourism is not relevant to my personal/professional context",
                { value: "other", text: "Other (please specify)", requiresInput: true }
            ],
            required: false,
            logic: {
                showOnlyIf: { 
                    question: "q43", 
                    values: ["None of the above"] 
                }
            }
        },
        {
            id: "q50",
            section: "action",
            type: "open-ended",
            text: "What would need to change about LTA's marketing, offerings, or approach to motivate you to take action?",
            rationale: "Solution-oriented question to gather actionable recommendations for driving conversion.",
            required: false,
            inputType: "textarea",
            placeholder: "Describe what would motivate you to take action...",
            logic: {
                showOnlyIf: { 
                    question: "q43", 
                    values: ["None of the above"] 
                }
            }
        },
        {
            id: "q51",
            section: "action",
            type: "open-ended",
            text: "Is there a specific call-to-action, offer, or initiative that would motivate you to engage with Limpopo tourism in the next 6-12 months?",
            rationale: "Tests potential activation strategies and identifies motivation levers.",
            required: false,
            inputType: "textarea",
            placeholder: "Describe what would motivate you to engage...",
            logic: {
                showOnlyIf: { 
                    question: "q43", 
                    values: ["None of the above"] 
                }
            }
        },
        {
            id: "q52",
            section: "action",
            type: "single-select",
            text: "Have LTA's initiatives resulted in tangible business outcomes for you or your organization?",
            rationale: "Quantifies business impact for industry stakeholders, measuring economic value generation.",
            options: [
                "Yes, significant positive business outcomes",
                "Yes, moderate positive business outcomes",
                "Yes, minimal positive business outcomes",
                "No impact on business outcomes",
                "Negative impact on business outcomes",
                "Too early to assess impact",
                "Not applicable to my role"
            ],
            required: false,
            logic: {
                showOnlyIf: { 
                    question: "q1", 
                    values: [
                        "Tourism Industry Operator (accommodation, tours, activities, attractions)",
                        "Trade & Distribution Partner (travel agent, tour operator, airline, transport, OTA, loyalty program)",
                        "Regional/Municipal Tourism Representative (RTO, municipal tourism office)"
                    ] 
                }
            }
        },
        {
            id: "q53",
            section: "action",
            type: "single-select",
            text: "How would you rate LTA's accessibility and responsiveness when you or your organization has needed information, support, or partnership engagement?",
            rationale: "Evaluates stakeholder relationship quality and service delivery.",
            options: [
                "Very poor - Inaccessible or unresponsive",
                "Poor - Difficult to reach, slow responses",
                "Fair - Adequate but room for improvement",
                "Good - Generally accessible and responsive",
                "Excellent - Highly accessible and responsive",
                "Not applicable - Haven't attempted to contact LTA"
            ],
            required: false
        },

        // ===== SECTION 5: ADVOCACY =====
        {
            id: "q54",
            section: "advocacy",
            type: "nps",
            text: "How likely are you to recommend Limpopo as a tourism destination to others (clients, colleagues, friends, family)?",
            rationale: "Net Promoter Score measurement to assess advocacy potential.",
            scale: {
                min: 0,
                max: 10,
                labels: {
                    0: "Not at all likely",
                    10: "Extremely likely"
                }
            },
            required: false
        },
        {
            id: "q55",
            section: "advocacy",
            type: "open-ended",
            text: "Please explain the primary reason for your score in Q54. What drives your likelihood (or lack thereof) to recommend Limpopo?",
            rationale: "Qualitative depth on NPS drivers to understand what builds or undermines advocacy.",
            required: false,
            inputType: "textarea",
            placeholder: "Explain what drives your likelihood to recommend Limpopo..."
        },
        {
            id: "q56",
            section: "advocacy",
            type: "single-select",
            text: "In the past 12 months, have you actively recommended or referred Limpopo to others?",
            rationale: "Measures actual advocacy behavior versus intent.",
            options: [
                "Yes, frequently (5+ times)",
                "Yes, occasionally (2-4 times)",
                "Yes, once",
                "No, but I intend to in the future",
                "No, and I don't intend to",
                "Not applicable to my role"
            ],
            required: false
        },
        {
            id: "q57",
            section: "advocacy",
            type: "open-ended",
            text: "When you recommended Limpopo, what specific aspects or offerings did you emphasize? What made you confident enough to advocate for the destination?",
            rationale: "Identifies advocacy messaging and confidence drivers for amplification.",
            required: false,
            inputType: "textarea",
            placeholder: "Describe what you emphasized when recommending Limpopo...",
            logic: {
                showOnlyIf: { 
                    question: "q56", 
                    values: ["Yes, frequently (5+ times)", "Yes, occasionally (2-4 times)", "Yes, once"] 
                }
            }
        },
        {
            id: "q58",
            section: "advocacy",
            type: "open-ended",
            text: "What prevents you from recommending Limpopo to others? What would need to change to make you a confident advocate?",
            rationale: "Diagnoses advocacy barriers to inform strategies for building ambassadors.",
            required: false,
            inputType: "textarea",
            placeholder: "Describe what prevents you from recommending Limpopo...",
            logic: {
                showOnlyIf: { 
                    question: "q56", 
                    value: "No, and I don't intend to" 
                }
            }
        },
        {
            id: "q59",
            section: "advocacy",
            type: "multiple-select",
            text: "Have you created or shared any content about Limpopo tourism in the past 12 months?",
            rationale: "Measures earned media and content creation, indicators of deep engagement.",
            options: [
                "Social media posts (personal or professional accounts)",
                "Blog articles or website content",
                "Professional articles or media coverage",
                "Photos or videos shared publicly",
                "Reviews on travel platforms (TripAdvisor, Google, etc.)",
                "Testimonials or case studies",
                "Presentations or conference talks",
                "Word-of-mouth conversations (not documented)",
                "Shared LTA's content with my networks",
                "None of the above"
            ],
            required: false
        },
        {
            id: "q60",
            section: "advocacy",
            type: "single-select",
            text: "How 'shareable' or 'Instagram-worthy' would you rate Limpopo's tourism experiences and attractions?",
            rationale: "Evaluates social media and viral potential, critical in digital age.",
            options: [
                "Not shareable at all - Lacks visual appeal or story-worthy moments",
                "Slightly shareable - Limited share-worthy content",
                "Moderately shareable - Some good content opportunities",
                "Very shareable - Strong visual appeal and story potential",
                "Extremely shareable - Highly compelling, must-share experiences",
                "Unable to assess"
            ],
            required: false
        },
        {
            id: "q61",
            section: "advocacy",
            type: "open-ended",
            text: "What specific Limpopo experiences, locations, or moments have the highest 'shareability' factor? What makes them compelling content?",
            rationale: "Identifies content gold mines for LTA to feature and promote.",
            required: false,
            inputType: "textarea",
            placeholder: "Describe highly shareable Limpopo experiences..."
        },
        {
            id: "q62",
            section: "advocacy",
            type: "single-select",
            text: "Would you be willing to partner with or support LTA on future marketing initiatives, content creation, or events?",
            rationale: "Identifies partnership appetite and preferred engagement models for stakeholder activation.",
            options: [
                "Yes, definitely interested in partnership/collaboration",
                "Yes, possibly interested depending on the opportunity",
                "Neutral - would need more information",
                "Probably not interested",
                "Definitely not interested",
                "Not applicable to my role/circumstances"
            ],
            required: false
        },
        {
            id: "q63",
            section: "advocacy",
            type: "likert-scale",
            text: "On a scale of 1-7, how proud are you to be associated with or to promote Limpopo tourism?",
            rationale: "Measures emotional connection and pride, strong predictor of authentic advocacy.",
            options: [
                { value: "1", label: "1 - Not at all proud" },
                { value: "2", label: "2" },
                { value: "3", label: "3" },
                { value: "4", label: "4 - Moderately proud" },
                { value: "5", label: "5" },
                { value: "6", label: "6" },
                { value: "7", label: "7 - Extremely proud" },
                { value: "not_applicable", label: "Not applicable" }
            ],
            required: false
        },
        {
            id: "q64",
            section: "advocacy",
            type: "open-ended",
            text: "What would transform you into an enthusiastic brand ambassador for Limpopo tourism? What would make you want to actively champion the destination?",
            rationale: "Solution-oriented question to identify levers for building passionate advocates.",
            required: false,
            inputType: "textarea",
            placeholder: "Describe what would make you an enthusiastic brand ambassador..."
        },

        // ===== SECTION 6: STRATEGIC EVALUATION & OPTIMIZATION =====
        {
            id: "q65",
            section: "optimization",
            type: "matrix",
            text: "Please rate LTA's overall marketing effectiveness across the following dimensions:",
            rationale: "Comprehensive quantitative assessment across key marketing dimensions.",
            rows: [
                "Creative quality and appeal of campaigns",
                "Message clarity and consistency",
                "Reach and frequency of communications",
                "Relevance to target markets",
                "Channel selection and media mix",
                "Timing and seasonality of campaigns",
                "Integration across touchpoints (360-degree approach)",
                "Digital and social media presence",
                "Content quality and usefulness",
                "Call-to-action clarity and effectiveness",
                "Brand positioning and differentiation",
                "Value proposition communication",
                "Return on investment (your perception)",
                "Innovation and fresh thinking",
                "Authenticity and credibility"
            ],
            columns: [
                "Very poor",
                "Poor",
                "Fair",
                "Good",
                "Excellent",
                "Unable to assess"
            ],
            required: false
        },
        {
            id: "q66",
            section: "optimization",
            type: "multiple-select",
            text: "Which marketing channels do you believe are delivering the BEST results for LTA in reaching and engaging target markets?",
            rationale: "Identifies most effective channels to optimize budget allocation.",
            options: [
                "Television advertising",
                "Radio advertising",
                "Print advertising (newspapers, magazines)",
                "Outdoor/billboard advertising",
                "Digital display advertising",
                "Social media (organic content)",
                "Social media (paid advertising)",
                "Search engine marketing (Google Ads, SEO)",
                "LTA website and digital platforms",
                "Email marketing and newsletters",
                "Content marketing (blogs, articles, videos)",
                "Influencer partnerships",
                "Public relations and media coverage",
                "Trade shows and exhibitions",
                "Industry events and forums",
                "Experiential activations and events",
                "Partnership marketing (airlines, hotels, tour operators)",
                "Word of mouth and referrals",
                "Tourism product operators' own marketing",
                { value: "other", text: "Other (please specify)", requiresInput: true }
            ],
            required: false,
            maxSelections: 5
        },
        {
            id: "q67",
            section: "optimization",
            type: "open-ended",
            text: "Conversely, which channels do you believe are UNDERPERFORMING or delivering insufficient return on investment?",
            rationale: "Identifies areas for reduction or elimination to reallocate resources.",
            required: false,
            inputType: "textarea",
            placeholder: "Describe underperforming channels..."
        },
        {
            id: "q68",
            section: "optimization",
            type: "single-select",
            text: "How would you rate the VARIETY and APPEAL of LTA's event programming (Tourism Month, Heritage Festival, exhibitions, activations, etc.)?",
            rationale: "Evaluates event programming quality and diversity.",
            options: [
                "Very poor - Insufficient variety, limited appeal",
                "Poor - Some variety but mostly unappealing",
                "Fair - Adequate variety and moderate appeal",
                "Good - Good variety with strong appeal",
                "Excellent - Diverse, highly appealing event portfolio",
                "Not sufficiently aware of LTA's event programming"
            ],
            required: false
        },
        {
            id: "q69",
            section: "optimization",
            type: "open-ended",
            text: "What types of events or initiatives should LTA introduce, expand, or eliminate to better engage target markets?",
            rationale: "Crowdsources expert recommendations for event portfolio optimization.",
            required: false,
            inputType: "textarea",
            placeholder: "Please consider:\n- Events/initiatives to ADD:\n- Events/initiatives to EXPAND:\n- Events/initiatives to ELIMINATE or REDUCE:"
        },
        {
            id: "q70",
            section: "optimization",
            type: "matrix",
            text: "How effective are LTA's partnerships and collaborations with the following entities?",
            rationale: "Evaluates partnership strategy effectiveness to identify strong and weak collaborations.",
            rows: [
                "South African Tourism (SAT)",
                "Brand South Africa",
                "SANParks (Kruger, Marakele, Mapungubwe)",
                "Regional Tourism Organizations (RTOs)",
                "Limpopo municipalities",
                "Private sector tourism operators (accommodations, tours, attractions)",
                "Airlines and transport operators",
                "Travel trade (tour operators, travel agents)",
                "Media organizations",
                "Influencers and content creators",
                "Academic and research institutions",
                "SADC tourism agencies",
                "Other provincial tourism agencies",
                "Community tourism organizations"
            ],
            columns: [
                "Very ineffective",
                "Ineffective",
                "Moderately effective",
                "Very effective",
                "Extremely effective",
                "Unaware of these partnerships"
            ],
            required: false
        },
        {
            id: "q71",
            section: "optimization",
            type: "open-ended",
            text: "What partnership opportunities is LTA missing? Who should LTA be partnering with that they aren't currently?",
            rationale: "Identifies untapped partnership potential for expanded reach and impact.",
            required: false,
            inputType: "textarea",
            placeholder: "Describe missing partnership opportunities..."
        },
        {
            id: "q72",
            section: "optimization",
            type: "likert-scale",
            text: "LTA's strategic objective is to position Limpopo as 'a leading tourism destination in Southern Africa.' How successfully do you believe LTA is achieving this vision?",
            rationale: "Measures perceived progress toward stated vision.",
            options: [
                { value: "1", label: "1 - Not at all successfully" },
                { value: "2", label: "2" },
                { value: "3", label: "3" },
                { value: "4", label: "4 - Moderately successfully" },
                { value: "5", label: "5" },
                { value: "6", label: "6" },
                { value: "7", label: "7 - Extremely successfully" }
            ],
            required: false
        },
        {
            id: "q73",
            section: "optimization",
            type: "open-ended",
            text: "What is the SINGLE MOST IMPORTANT strategic shift or action LTA should take to accelerate progress toward becoming a leading destination in Southern Africa?",
            rationale: "Forces prioritization of most impactful strategic recommendation.",
            required: false,
            inputType: "textarea",
            placeholder: "Describe the single most important strategic shift..."
        },
        {
            id: "q74",
            section: "optimization",
            type: "matrix",
            text: "LTA has identified several strategic weaknesses. From your expert perspective, please rate the URGENCY of addressing each:",
            rationale: "Prioritizes strategic challenges for focused resource allocation.",
            rows: [
                "Low market capture (only 2% international, 5% African, 9% domestic)",
                "Brand fragmentation and 'best kept secret' positioning",
                "Limited differentiation from other SA provinces",
                "Eco-tourism-only perception (lacking broader appeal)",
                "Insufficient integration with municipalities and RTOs",
                "Limited reach in key source markets (Gauteng, SADC, international)",
                "Failure to convert VFR travel to leisure spending",
                "Information accessibility and availability gaps",
                "Awareness-to-action conversion barriers",
                "Limited nightlife and shopping offerings for SADC markets",
                "Infrastructure and accessibility concerns"
            ],
            columns: [
                "Not urgent - Low priority",
                "Somewhat urgent",
                "Moderately urgent",
                "Very urgent - High priority",
                "Critically urgent - Immediate priority",
                "Not actually a weakness / Not applicable"
            ],
            required: false
        },
        {
            id: "q75",
            section: "optimization",
            type: "multiple-select",
            text: "Which market segments represent the GREATEST UNTAPPED OPPORTUNITY for Limpopo tourism growth?",
            rationale: "Identifies highest-potential growth segments for focused targeting.",
            options: [
                "International leisure travelers (beyond current US/UK/Germany focus)",
                "SADC countries beyond Zimbabwe (Mozambique, Botswana, Angola, etc.)",
                "Domestic leisure travelers (converting from VFR to active tourism)",
                "Weekend break market from Gauteng and neighboring provinces",
                "Limpopo residents (exploring their own province)",
                "Expats visiting from abroad",
                "Airmile/loyalty program members looking to burn points",
                "Budget travelers seeking value destinations",
                "Luxury travelers seeking exclusive experiences",
                "Adventure and outdoor enthusiasts",
                "Wellness and R&R seekers",
                "Business and MICE market",
                "Cultural and heritage tourists",
                "Multigenerational family travelers",
                "Solo travelers",
                "Young couples and honeymooners",
                "Retirees with time and resources",
                "Faith-based/religious tourism",
                { value: "other", text: "Other (please specify)", requiresInput: true }
            ],
            required: false,
            maxSelections: 3
        },
        {
            id: "q76",
            section: "optimization",
            type: "open-ended",
            text: "For the top untapped opportunity segment(s) you identified in Q75, what specific marketing strategies or tactics would effectively reach and convert them?",
            rationale: "Gathers tactical recommendations for priority segment penetration.",
            required: false,
            inputType: "textarea",
            placeholder: "Describe specific strategies for your selected opportunity segments..."
        },
        {
            id: "q77",
            section: "optimization",
            type: "matrix",
            text: "How well is LTA demonstrating its stated core values through its marketing and stakeholder engagement?",
            rationale: "Evaluates whether LTA's actions align with stated values, building trust and credibility.",
            rows: [
                "Integrity (conduct beyond reproach)",
                "Respect (effective listening, understanding stakeholders)",
                "Excellence (service excellence delivery)",
                "Responsibility/Facilitation (sustainable economic, social, environmental growth)",
                "Communication (effective internal and external communication)",
                "Accountability (transparent actions and results)",
                "Learning Organization (continuous improvement, best practices)"
            ],
            columns: [
                "Not demonstrated at all",
                "Poorly demonstrated",
                "Adequately demonstrated",
                "Well demonstrated",
                "Excellently demonstrated",
                "Unable to assess"
            ],
            required: false
        },
        {
            id: "q78",
            section: "optimization",
            type: "single-select",
            text: "Thinking about LTA's theme 'Tourism and Sustainable Transformation,' how effectively is this theme being translated into tangible initiatives and outcomes that stakeholders can see and measure?",
            rationale: "Tests whether thematic positioning translates to credible action and outcomes.",
            options: [
                "Not effectively at all - It's just rhetoric without substance",
                "Slightly effectively - Minimal visible action",
                "Moderately effectively - Some visible initiatives",
                "Very effectively - Strong translation into action",
                "Extremely effectively - Clear, measurable sustainable transformation",
                "Unable to assess"
            ],
            required: false
        },
        {
            id: "q79",
            section: "optimization",
            type: "open-ended",
            text: "What role should local communities and Limpopo residents play in tourism marketing and development, and how effectively is LTA engaging them?",
            rationale: "Explores community engagement strategy and effectiveness, critical for authentic tourism.",
            required: false,
            inputType: "textarea",
            placeholder: "Describe the role of local communities and LTA's engagement..."
        },
        {
            id: "q80",
            section: "optimization",
            type: "open-ended",
            text: "From your professional perspective, what is ONE THING LTA is doing exceptionally well that should be protected, amplified, and celebrated?",
            rationale: "Identifies strengths to maintain and leverage, ensuring optimization doesn't eliminate what's working.",
            required: false,
            inputType: "textarea",
            placeholder: "Describe one thing LTA is doing exceptionally well..."
        },
        {
            id: "q81",
            section: "optimization",
            type: "open-ended",
            text: "From your professional perspective, what is THE ONE CRITICAL IMPROVEMENT that would have the maximum impact on LTA's effectiveness?",
            rationale: "Forces prioritization of single highest-impact improvement for focused action.",
            required: false,
            inputType: "textarea",
            placeholder: "Describe the one critical improvement with maximum impact..."
        },
        {
            id: "q82",
            section: "optimization",
            type: "open-ended",
            text: "If you were appointed as a strategic advisor to LTA's executive team with the mandate to optimize their marketing and positioning, what would be your top 3-5 strategic recommendations?",
            rationale: "Invites comprehensive strategic counsel from expert stakeholders.",
            required: false,
            inputType: "textarea",
            placeholder: "Please prioritize and be as specific as possible with 3-5 recommendations..."
        },
        {
            id: "q83",
            section: "optimization",
            type: "open-ended",
            text: "Are there any innovative approaches, campaigns, or strategies from other tourism destinations (in South Africa or globally) that you believe LTA should study or adapt?",
            rationale: "Crowdsources competitive intelligence and best practice examples.",
            required: false,
            inputType: "textarea",
            placeholder: "Please provide examples and explain why they would be relevant for Limpopo."
        },
        {
            id: "q84",
            section: "optimization",
            type: "single-select",
            text: "How important is it for LTA to have a strong digital and social media presence in today's tourism marketing landscape?",
            rationale: "Validates digital investment priority.",
            options: [
                "Not important at all",
                "Slightly important",
                "Moderately important",
                "Very important",
                "Critically important - Essential for success"
            ],
            required: false
        },
        {
            id: "q85",
            section: "optimization",
            type: "single-select",
            text: "How would you rate LTA's current digital and social media presence?",
            rationale: "Evaluates digital performance and gathers improvement recommendations.",
            options: [
                "Very poor - Weak or non-existent",
                "Poor - Exists but ineffective",
                "Fair - Adequate but not competitive",
                "Good - Strong and effective",
                "Excellent - Best-in-class, highly engaging",
                "Not familiar with LTA's digital presence"
            ],
            required: false
        },
        {
            id: "q86",
            section: "optimization",
            type: "open-ended",
            text: "Looking ahead to 2026 and beyond, what emerging trends, opportunities, or threats should LTA prioritize in their strategic planning?",
            rationale: "Forward-looking insights to inform future strategy development.",
            required: false,
            inputType: "textarea",
            placeholder: "Describe emerging trends, opportunities, or threats for LTA..."
        },

        // ===== CLOSING QUESTIONS =====
        {
            id: "q87",
            section: "optimization",
            type: "likert-scale",
            text: "On a scale of 1-10, what is your overall impression of the Limpopo Tourism Agency's work in destination marketing and tourism development?",
            rationale: "Overall sentiment measurement for holistic assessment.",
            options: [
                { value: "1", label: "1 - Very negative impression" },
                { value: "2", label: "2" },
                { value: "3", label: "3" },
                { value: "4", label: "4" },
                { value: "5", label: "5" },
                { value: "6", label: "6" },
                { value: "7", label: "7" },
                { value: "8", label: "8" },
                { value: "9", label: "9" },
                { value: "10", label: "10 - Very positive impression" }
            ],
            required: false
        },
        {
            id: "q88",
            section: "optimization",
            type: "open-ended",
            text: "In one word or short phrase, how would you describe LTA's greatest strength?",
            rationale: "Captures essence of what LTA does best for messaging and positioning.",
            required: false,
            inputType: "text",
            placeholder: "One word or short phrase..."
        },
        {
            id: "q89",
            section: "optimization",
            type: "open-ended",
            text: "In one word or short phrase, how would you describe LTA's greatest opportunity for improvement?",
            rationale: "Captures essence of priority improvement area for focused action.",
            required: false,
            inputType: "text",
            placeholder: "One word or short phrase..."
        },
        {
            id: "q90",
            section: "optimization",
            type: "open-ended",
            text: "Is there anything else you would like to share with LTA about their marketing, events, partnerships, or overall approach to positioning Limpopo as a tourism destination?",
            rationale: "Catch-all for any insights not captured by structured questions.",
            required: false,
            inputType: "textarea",
            placeholder: "Your additional insights, suggestions, or observations are welcome here."
        },
        {
            id: "q91",
            section: "optimization",
            type: "single-select",
            text: "Would you be willing to participate in a follow-up interview or focus group discussion to explore any of these topics in greater depth?",
            rationale: "Recruits participants for qualitative deep-dive research.",
            options: [
                "Yes, I would be interested in participating",
                "Maybe, depending on timing and format",
                "No, thank you"
            ],
            required: false
        }
    ],

    // ===== COMPREHENSIVE SKIP LOGIC =====
    skipLogic: {
        // Q5: No exposure routing
        "q5_No_exposure": {
            from: "q5",
            condition: { value: "No exposure (have not encountered LTA content/initiatives)" },
            action: "skipTo",
            target: { section: "screening", question: "q7" },
            then: { section: "optimization", question: "q65" }
        },

        // Q6: Only show if Q5 indicates some exposure
        "q6_show_condition": {
            from: "q5",
            condition: { notValue: "No exposure (have not encountered LTA content/initiatives)" },
            action: "show",
            target: "q6"
        },

        // Q8-Q30: Only show if some exposure in Q5
        "awareness_section_condition": {
            from: "q5",
            condition: { notValue: "No exposure (have not encountered LTA content/initiatives)" },
            action: "showSection",
            target: "q8-q30"
        },

        // Q11: Only show if some awareness of theme in Q10
        "q11_show_condition": {
            from: "q10",
            condition: { 
                notValues: ["Not clear at all - I don't understand what this theme means", "Not aware of this theme"] 
            },
            action: "show",
            target: "q11"
        },

        // Q18: Only show if aware of positioning in Q17
        "q18_show_condition": {
            from: "q17",
            condition: { value: "Yes, I'm aware of this positioning" },
            action: "show",
            target: "q18"
        },

        // Q22: Only show if moderate+ awareness in Q9
        "q22_show_condition": {
            from: "q9",
            condition: { hasMatrixResponse: true, minAwareness: "Somewhat aware (know basic details)" },
            action: "show",
            target: "q22"
        },

        // Q29: Only show if memorability rating 4+ in Q28
        "q29_show_condition": {
            from: "q28",
            condition: { value: ["4", "5", "6", "7"] },
            action: "show",
            target: "q29"
        },

        // Q32: Only show if no consideration in Q31
        "q32_show_condition": {
            from: "q31",
            condition: { values: ["No, I have not actively considered Limpopo despite awareness"] },
            action: "show",
            target: "q32"
        },

        // Q40: Only show if information inadequate in Q39
        "q40_show_condition": {
            from: "q39",
            condition: { 
                values: ["Severely inadequate - Critical information is missing or hard to find", "Somewhat inadequate - Important gaps in available information"] 
            },
            action: "show",
            target: "q40"
        },

        // Action routing based on Q43
        "q43_actions_taken": {
            from: "q43",
            condition: { includesAny: true, notValues: ["None of the above"] },
            action: "showSection",
            target: "q44-q48"
        },

        "q43_no_actions": {
            from: "q43",
            condition: { values: ["None of the above"] },
            action: "showSection",
            target: "q49-q51"
        },

        // Q44-Q48: Only show if actions taken
        "action_details_condition": {
            from: "q43",
            condition: { includesAny: true, notValues: ["None of the above"] },
            action: "showSection",
            target: "q44-q48"
        },

        // Q49-Q51: Only show if no actions
        "no_action_details_condition": {
            from: "q43",
            condition: { values: ["None of the above"] },
            action: "showSection",
            target: "q49-q51"
        },

        // Q52: Only show for industry operators and trade partners
        "q52_stakeholder_condition": {
            from: "q1",
            condition: { 
                values: [
                    "Tourism Industry Operator (accommodation, tours, activities, attractions)",
                    "Trade & Distribution Partner (travel agent, tour operator, airline, transport, OTA, loyalty program)",
                    "Regional/Municipal Tourism Representative (RTO, municipal tourism office)"
                ] 
            },
            action: "show",
            target: "q52"
        },

        // Q57: Only show if recommended in Q56
        "q57_show_condition": {
            from: "q56",
            condition: { values: ["Yes, frequently (5+ times)", "Yes, occasionally (2-4 times)", "Yes, once"] },
            action: "show",
            target: "q57"
        },

        // Q58: Only show if won't recommend in Q56
        "q58_show_condition": {
            from: "q56",
            condition: { value: "No, and I don't intend to" },
            action: "show",
            target: "q58"
        },

        // Ghost flow - direct to strategic evaluation if no exposure
        "ghost_flow_optimization": {
            from: "q7",
            condition: { 
                parentCondition: { question: "q5", value: "No exposure (have not encountered LTA content/initiatives)" } 
            },
            action: "skipTo",
            target: { section: "optimization", question: "q65" }
        }
    },

    // ===== ANALYSIS METRICS CONFIGURATION =====
    analysisMetrics: {
        awareness: {
            unaidedRecall: "q8",
            aidedRecall: "q9", 
            themeUnderstanding: "q10",
            productClusterAwareness: "q12",
            keyDifferentiators: "q13",
            brandAssociations: "q14",
            differentiationScore: "q15",
            positioningAwareness: "q17",
            positioningEffectiveness: "q18",
            channelEffectiveness: "q19"
        },
        interest: {
            interestGenerated: "q20",
            eventAppeal: "q21", 
            standoutEvents: "q22",
            programmingGaps: "q23",
            positioningAppeal: "q24",
            segmentAlignment: "q25",
            underservedSegments: "q26",
            valuePropositionRanking: "q27",
            memorability: "q28",
            memorableElements: "q29",
            ineffectiveElements: "q30"
        },
        consideration: {
            considerationTypes: "q31",
            conversionBarriers: "q32",
            valuePropositionComparison: "q33",
            competitivePositioning: "q34",
            marketNeedsAddressment: "q35",
            marketCaptureLimits: "q36",
            vfrConversionEffectiveness: "q37",
            vfrConversionStrategies: "q38",
            informationAdequacy: "q39",
            informationGaps: "q40",
            brandDifferentiation: "q41",
            positioningStatement: "q42"
        },
        action: {
            actionTypes: "q43",
            ltaInfluencedActions: "q44",
            conversionStories: "q45",
            conversionFactors: "q46",
            satisfaction: "q47",
            experienceQuality: "q48",
            nonConversionReasons: "q49",
            conversionMotivators: "q50",
            activationTriggers: "q51",
            businessImpact: "q52",
            stakeholderService: "q53"
        },
        advocacy: {
            nps: "q54",
            npsDrivers: "q55",
            referralBehavior: "q56",
            advocacyMessaging: "q57",
            advocacyBarriers: "q58",
            contentCreation: "q59",
            shareability: "q60",
            shareableContent: "q61",
            partnershipInterest: "q62",
            prideAssociation: "q63",
            ambassadorMotivators: "q64"
        },
        strategic: {
            marketingEffectiveness: "q65",
            bestChannels: "q66",
            underperformingChannels: "q67",
            eventProgramming: "q68",
            eventOptimization: "q69",
            partnershipEffectiveness: "q70",
            partnershipOpportunities: "q71",
            visionAchievement: "q72",
            strategicShift: "q73",
            weaknessPrioritization: "q74",
            growthOpportunities: "q75",
            segmentStrategies: "q76",
            valuesDemonstration: "q77",
            sustainableTransformation: "q78",
            communityEngagement: "q79",
            keyStrengths: "q80",
            criticalImprovements: "q81",
            strategicRecommendations: "q82",
            competitiveIntelligence: "q83",
            digitalImportance: "q84",
            digitalPerformance: "q85",
            futureTrends: "q86",
            overallImpression: "q87",
            greatestStrength: "q88",
            improvementPriority: "q89",
            additionalInsights: "q90",
            followupInterest: "q91"
        }
    },

    // ===== STAKEHOLDER-SPECIFIC ROUTING =====
    stakeholderRouting: {
        "Marketing & Communications Professional": {
            emphasis: ["q65", "q66", "q67", "q84", "q85"],
            optional: ["q52"]
        },
        "Event Management & Experience Design Specialist": {
            emphasis: ["q21", "q22", "q23", "q68", "q69"],
            optional: ["q52"]
        },
        "Tourism Industry Operator": {
            emphasis: ["q52", "q53", "q74", "q75", "q76"],
            optional: []
        },
        "Trade & Distribution Partner": {
            emphasis: ["q52", "q53", "q75", "q76"],
            optional: []
        },
        "Regional/Municipal Tourism Representative": {
            emphasis: ["q52", "q53", "q70", "q79"],
            optional: []
        },
        "Content Creator & Media": {
            emphasis: ["q59", "q60", "q61", "q62"],
            optional: ["q52"]
        },
        "Academic & Research Expert": {
            emphasis: ["q36", "q37", "q38", "q77", "q78"],
            optional: ["q52"]
        }
    }
};

// Export for use in other modules
if (typeof module !== 'undefined' && module.exports) {
    module.exports = { LTA_QUESTIONNAIRE };
}
